/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.server;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author rocco
 */
public class ManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageFrame
     */
    public ManageFrame() {
        initComponents();
    }
    
    public void addClient(String client_name) {
        System.out.println("chiamata add Client");
        
        // aggiungi etichetta relativa al client
        JLabel label = new JLabel(client_name);
        label.setForeground(Color.BLACK);
        manage_panel.add(label);
        
        // aggiungi bottone per disconnettere il client
        JButton disconnect_button = new JButton();
        disconnect_button.setText("Disconnetti");
        disconnect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnect_client();
            }
        });
        
        manage_panel.add(disconnect_button);
        
        
        
        
        manage_panel.revalidate();
        manage_panel.repaint();
    }
    
    private void disconnect_client() {
        System.out.println("disconnessione del client..."); // aggiungi info relative al client
        // Server.diconnectClient(client_socket);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manage_panel = new javax.swing.JPanel();
        shutdown_server_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manage_panel.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(manage_panel, java.awt.BorderLayout.CENTER);

        shutdown_server_button.setText("Spegni server");
        shutdown_server_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdown_server_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(shutdown_server_button, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shutdown_server_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdown_server_buttonActionPerformed
        // TODO add your handling code here:
        Server.closeServer();
    }//GEN-LAST:event_shutdown_server_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manage_panel;
    private javax.swing.JButton shutdown_server_button;
    // End of variables declaration//GEN-END:variables
}
